name: Chapter 04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Build Zig
        run: |
            zig build-exe ch04/eql_sent.zig
            zig build-exe ch04/arr_to_sent.zig
            zig build-exe ch04/sent_arr.zig
            zig build-exe ch04/search_sent.zig
            zig build-exe ch04/length_sent.zig
            zig build-exe ch04/split_sent.zig
            zig build-exe ch04/copy_sent.zig
            zig build-exe ch04/sent_to_str.zig
            zig build-exe ch04/slicing_arr.zig
            zig build-exe ch04/transpose.zig
            zig build-exe ch04/multidim_iter.zig
            zig build-exe ch04/sent_to_slice.zig
            zig build-exe ch04/slice_alloc.zig
            zig build-exe ch04/tester.zig
            zig build-exe ch04/concat_sent.zig
            zig build-exe ch04/reshape.zig
            zig build-exe ch04/sent_slice.zig
            zig build-exe ch04/dynArray.zig
            zig build-exe ch04/rev_sent.zig
            zig build-exe ch04/flatten.zig
            zig build-exe ch04/multidim.zig
      - name: Test Zig
        run: | 
            zig test ch04/exercises/exercise1.zig
            zig test ch04/exercises/exercise2.zig
            zig test ch04/exercises/exercise3.zig        
      - name: Build C 
        run: |
            zig cc ch04/dynArray.c
            zig cc ch04/sentinel.c
            zig cc ch04/slice_alloc.c