name: Readme 

on:
  push:
    branches:
      - main

jobs:
  run-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Go file
        run: go run readme.go

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"
          git add .
          git commit -m "Update from GitHub Action"
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.REPO_ACCESS }}@${{ github.event.repository.clone_url }}
          git push

